[tools]
node = "latest"
python = "latest"
yarn = "1"
rust = "latest"
"npm:safe-rm" = "latest"
uv = "latest"
bun = "latest"
"npm:pyright" = "latest"
"npm:ccusage" = "latest"
"cargo:yui-cli" = "latest"
# "npm:@helpfeel/cosense-cli" = "latest"
"npm:@earendil-works/pi-coding-agent" = { version = "latest", minimum_release_age = "0s" }
"npm:markdownlint-cli" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
gcloud = "latest"
"pipx:httpie" = "latest"
"pipx:headroom-ai" = { version = "latest", extras = ["all"] }
"pipx:poetry" = "latest"
redis = "latest"
"npm:@opencode-ai/cli" = "1"
micro = "latest"
pnpm = "latest"
"github:can1357/oh-my-pi" = { version = "latest", minimum_release_age = "0s" }
"npm:@robzolkos/lazypi" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "node"]
