[tools]
node = "latest"
"npm:@github/copilot" = "latest"
python = "latest"
yarn = "1"
"npm:difit" = "latest"
rust = "latest"
"npm:safe-rm" = "latest"
uv = "latest"
"npm:oh-my-opencode-slim" = "latest"
bun = "latest"
"npm:pyright" = "latest"
"npm:opencode-ai" = "latest"
"npm:ccusage" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python", "node"]
