[tools]
"aqua:openai/codex" = "latest"
chezmoi = "latest"
colima = "latest"
delta = "latest"
eza = "latest"
fzf = "latest"
gemini = "latest"
gh = "latest"
ghq = "latest"
lazygit = "latest"
node = "25.2"
"npm:@anthropic-ai/claude-code" = "latest"
opencode = "latest"
pipx = "latest"
python = "latest"
ripgrep = "latest"
sqlite = "latest"
tmux = "latest"
uv = "latest"
zoxide = "latest"

[shell_alias]
apap = "brew update && brew upgrade && mise up && brew cleanup"
history = "history -Di"
reload = "exec $SHELL -l"
ls = "eza --time-style=long-iso --hyperlink -F always --git --icons auto"
ll = "ls -lhg"
la = "ls -lhga"
lt = "ls --tree --git-ignore"

