#theme = "catppuccin_mocha"
#theme = "catppuccin_frappe"
theme = "catppuccin_frappe_transparent"

[editor]
clipboard-provider = "pasteboard"

[editor.whitespace]
render = "all"

[editor.soft-wrap]
enable = false

[keys.normal]
"A-z" = ":toggle soft-wrap.enable"
y = ["yank", "yank_to_clipboard"]

[keys.insert]
"C-[" = "normal_mode"

[keys.select]
y = ["yank", "yank_to_clipboard"]
